[package]
name = "rt1w"
version = "0.1.0"
authors = ["Ramon Imbao <ramonimbao@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.1"
image = "0.20.1"
serde_json = "1.0.33"
structopt = "0.2.14"
time = "0.1.41"
stl_io = "0.4.2"